version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_ALLOW_ORIGIN=*

  app:
    image: ragservice
    container_name: rag_service
    ports:
      - "8090:8090"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - qdrant

volumes:
  qdrant_data:
